### ISSUE TITLE
more index.php clean up

### ISSUE THREAD

**Issue by samsonasik** [gianarb/penny-classic-app#20]
I think to make more clean up public/index.php, we can do:
- move template call in own Controller Abstract, and make Controller Container aware as shortcut-able ( while dependency injection is preferable).
- move app->attach call inside app->run() or other fuction that initialize app event

**Comment by gianarb** [comment]
This point is very important
- move app->attach call inside app->run() or other fuction that initialize app event

The bootstrap event is required and at the moment we don't manage it.
my idea is, run func trigger a bootstrap event and we can attach it (by dependence injection) default listener.. 

About this point
- move template call in own Controller Abstract, and make Controller Container aware as shortcut-able ( while dependency injection is preferable).

In my opinion current controller is very easy because it doesn't extends nothing and I love this implementation.. :) I'm very happy to share another application with a different approach.. :) Maybe we can add it into the organization if you are interested :+1:

**Comment by samsonasik** [comment]
Ok, I'm +1 for adding that ;)

Warm regards,

Abdul Malik Ikhsan

Pada 14 Sep 2015, pukul 22.51, Gianluca Arbezzano notifications@github.com menulis:

**Comment by gianarb** [comment]
https://github.com/pennyphp/penny-classic-app/commit/3fc8ea114132446e9f3276a448923fbab33c344f
