### ISSUE TITLE
move npm install, bower install, and grunt dev to composer.json on post install

### ISSUE THREAD

**Issue by samsonasik** [gianarb/penny-classic-app#7]
I think it would be more great to have 1 command:

``` bash
$ composer create project gianarb/penny-classic-app
```

run web server, and done :D to avoid multi step to install.

to avoid node installation, for bower, i think we can use bowerphp ( i tried some time ago), and for grunt, _probably_ we can use gruntphp ( i didn't try)

**Comment by samsonasik** [comment]
oops, I am wrong about gruntphp :P

**Comment by gianarb** [comment]
Yeh mabe is a good idea 
@fntlnz what do you think?

I integrated this flow because IMO is a good way to manage css/js but it is very strong :muscle:

**Comment by fntlnz** [comment]
I haven't never liked the idea of doing all from php.
Bowerphp would be ok if we actually didn't have grunt. Since we already have grunt we already need nodejs.

So the reasoning is: if I already have node, why shouldn't I use node to do a thing that was born for node in favor of doing it using an "unofficial" implementation written in PHP?

Same for grunt-php, I don't think that a seasoned php developer would find handy to use an unknown grunt command over the well known _php -s_ to start the php built-in server.
On the other hand a new coming php developer might find it useful but this would hide the "php built-in server" feature making him think that it's just "grunt black magic".

However these are just my opinions.

**Comment by gianarb** [comment]
In my opinion we can add a note into the docs like:

"bower and grunt require node.js this is only an example of method to manage static asset, if you don't have familiarity with this tools no problem, you can use assetic, download all static deps into the public dir or other solutions"

**Comment by samsonasik** [comment]
@gianarb :+1: for add the note.

**Comment by fntlnz** [comment]
neat, LGTM

**Comment by gianarb** [comment]
https://github.com/pennyphp/penny-classic-app/commit/627be51ecbc107c30fae624b5e0077f4bd22654a
